android-interop-testing: add AndroidX Test core in implementation (#12718)
This alignment resolves a version skew issue that caused
NoClassDefFoundError crashes during instrumentation tests on Firebase
Test Lab.

Fixes
https://github.com/grpc/grpc-java/pull/12703#issuecomment-4088211068