Context: add test for the scenario that Context's logger itself is using Context
This will break if 2f6e2c87ab1aeda591fcb7764a8ad6bb20855a2a & a3a5420922ecf1ddc2c4ab77c273be3df47b74f5 are reverted:

```
> Task :grpc-context:test

io.grpc.ContextTest > testWrapCallable FAILED
    java.lang.ExceptionInInitializerError
        at io.grpc.ContextTest.<clinit>(ContextTest.java:83)

        Caused by:
        java.lang.RuntimeException: Storage override had failed to initialize
            at io.grpc.Context.storage(Context.java:134)
            at io.grpc.Context.current(Context.java:163)
            at io.grpc.ContextTest$1.publish(ContextTest.java:69)
            at java.util.logging.Logger.log(Logger.java:738)
            at java.util.logging.Logger.doLog(Logger.java:765)
            at java.util.logging.Logger.log(Logger.java:875)
            at io.grpc.Context.<clinit>(Context.java:122)
            ... 1 more
```