bazel: Fix Bazel 8 WORKSPACE support
There's some rearranging happening here, like moving jar_jar later. But
the main thing is downgrading rules_java to 8.15.2. rules_java 8.16 and
later somehow break protobuf:

```
	File ".../external/com_google_protobuf/bazel/private/proto_library_rule.bzl", line 43, column 17, in _get_import_prefix
		if not paths.is_normalized(import_prefix):
Error: 'struct' value has no field or method 'is_normalized'
Available attributes: basename, dirname, is_absolute, join, normalize, relativize, replace_extension, split_extension
```

https://github.com/protocolbuffers/protobuf/issues/17687 claims that
this is due to not using bazel_skylib 1.7.0, but protobuf_deps is
defining bazel_skylib to be 1.7.0 and nothing earlier seems to be
defining bazel_skylib. So we'll leave this as a bit of a mystery for
later. rules_java 8.15.2 is still newer than protobuf_deps's 8.6.1.