kokoro: Avoid brew on Mac OS (v1.80.x backport) (#12870)
Backport of #12846 to v1.80.x.
---
brew is failing with "Error: undefined method 'first' for nil" when
trying to upgrade itself. We already use Java 11 on other platforms, and
it is already available on the Kokoro machines. We swap to download
Maven just like we do for Linux, so then we can avoid brew entirely.

However, the pre-installed Java is an arm build whereas the brew install
was x86. So now the examples try to use
protoc-gen-grpc-java-1.82.0-SNAPSHOT-osx-aarch_64.exe which don't exist
because we used the default ARCH of x86_64. So now we also need to swap
the primary platform on OS X to aarch_64 and copy the x86_64 binaries
from that.

CC @shivaspeaks, feel free to review, since you worked on the universal
binaries

Co-authored-by: Eric Anderson <ejona@google.com>