examples: Use encouraged APIs and avoid over-specifying configuration
Also fix tcnative, which was the wrong version and would cause a crash
with NoSuchMethodError.