kokoro: Avoid brew on Mac OS
brew is failing with "Error: undefined method 'first' for nil" when
trying to upgrade itself. We already use Java 11 on other platforms, and
it is already available on the Kokoro machines. We swap to download
Maven just like we do for Linux, so then we can avoid brew entirely.

However, the pre-installed Java is an arm build whereas the brew install
was x86. So now the examples try to use
protoc-gen-grpc-java-1.82.0-SNAPSHOT-osx-aarch_64.exe which don't exist
because we used the default ARCH of x86_64. So now we also need to swap
the primary platform on OS X to aarch_64 and copy the x86_64 binaries
from that.